### ISSUE TITLE
whatr_board started failing around 2022-03-30

### ISSUE THREAD

**Issue by spkaluzny** [k5cents/whatr#11]
`whatr_board` starting failing around 2022-03-30. Get an error in `dplyr::bind_cols`

I suspect that the J! Archive may have made some changes on the site. The day before I noticed this error the J! Archive was not accessible on the web (through `whatr` functions or from a browser).

Reproduce:
```r
library(whatr)
packageVersion("whatr")
#> [1] ‘1.1.0’
whatr_board(5432)
#> Error in `dplyr::bind_cols()`:
#> ! Can't recycle `..1` (size 55) to match `..2` (size 56).
#> Run `rlang::last_error()` to see where the error occurred.
rlang::last_error()
#> error/vctrs_error_incompatible_size>
#> Error in `dplyr::bind_cols()`:
#> ! Can't recycle `..1` (size 55) to match `..2` (size 56).
#> ---
#> Backtrace:
#>  1. whatr::whatr_board(5432)
#>  2. whatr::whatr_answers(game)
#>  3. dplyr::bind_cols(whatr_order(game = game), answers)
#>  6. vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)
#> Run `rlang::last_trace()` to see the full context.
```

**Comment by k5cents** [comment]
I think this fixed the problem? I'm not sure exactly what changed, but I used to add the Final Jeopardy answer to the other answers manually, but now it seems to be included with the others (hence the 55 and 56 discrepancy in your reprex).

**Comment by spkaluzny** [comment]
On Wed, Apr 6, 2022 at 10:53 AM Kiernan Nicholls ***@***.***>
wrote:

> I think this fixed the problem? I'm not sure exactly what changed, but I
> used to add the Final Jeopardy answer to the other answers manually, but
> now it seems to be included with the others (hence the 55 and 56
> discrepancy in your reprex).
>
>
Yes, that fixed the problem with whatr_board failing. My scripts for
accessing the J! Archive using whatr are all now working again.
Thanks,
 Stephen
